WYCC: relocated the clib directory.

diff --git a/bin/wycc b/bin/wycc
--- a/bin/wycc
+++ b/bin/wycc
@@ -50,22 +50,19 @@ fi
 
 WHILEY_CLASSPATH=$CLASSPATH
 
-#
 # as there may more than one version of the jar files
 # it is important to first use the * expansion, and then
 # use the last one via the "##* " expansion.
-#
+
 for lib in $LIBS
 do
-    #JAR=$(ls $LIBDIR/$lib*.jar)
-    tmp=$(echo $LIBDIR/${lib}-v*.jar)
-    JAR=${tmp##* }
-    case "$JAR" in 
-    *\**)
-        echo "Library '$lib' not found"
-        exit 2
-        ;;
-    esac
+    JAR=$(ls $LIBDIR/$lib)
+    N=`echo $JAR | wc -w`
+    if [ 1 -ne $N ]; 
+    then
+	echo "*** ERROR: multiple versions of library $lib found in lib/"
+	exit 2
+    fi
     WHILEY_CLASSPATH="$JAR$PATHSEP$WHILEY_CLASSPATH"
 done
 
