added comparator functions fixed size bookkeeping on lists added recognition of Code.NewSet added usage in wycc wycc changed to deal with versions wycc changed to use -B -h -D wycc_lib changed to use calloc added support for Wy_Set

diff --git a/bin/wycc b/bin/wycc
--- a/bin/wycc
+++ b/bin/wycc
@@ -24,8 +24,9 @@
 ################
 
 DIR=`dirname "$0"`/..
+MyName=${0##*/}
 LIBDIR=$DIR/lib
-LIBS="wyc-v*.jar wyil-v*.jar wycc-v*.jar"
+LIBS="wyc wyil wycc"
 
 # check for running under cywin
 cygwin=false
@@ -48,17 +49,54 @@ fi
 
 WHILEY_CLASSPATH=$CLASSPATH
 
+#
+# as there may more than one version of the jar files
+# it is important to first use the * expansion, and then
+# use the last one via the "##* " expansion.
+#
 for lib in $LIBS
 do
-    JAR=$(ls $LIBDIR/$lib)
+    #JAR=$(ls $LIBDIR/$lib*.jar)
+    tmp=$(echo $LIBDIR/${lib}-v*.jar)
+    JAR=${tmp##* }
+    case "$JAR" in 
+    *\**)
+        echo "Library '$lib' not found"
+        exit 2
+        ;;
+    esac
     WHILEY_CLASSPATH="$JAR$PATHSEP$WHILEY_CLASSPATH"
 done
 
-WYRT_JAR=$(ls $LIBDIR/wyrt-v*.jar)
+#WYRT_JAR=$(ls $LIBDIR/wyrt-v*.jar)
+tmp=$(echo $LIBDIR/wyrt-v*.jar)
+WYRT_JAR=${tmp##* }
 WHILEY_BOOTPATH="$WYRT_JAR"
 
-WYCC=" -server -Xmx128M -cp $WHILEY_CLASSPATH wycc.WyccMain -bp $WHILEY_BOOTPATH"
+WYCC="java -server -Xmx128M -cp $WHILEY_CLASSPATH wycc.WyccMain -bp $WHILEY_BOOTPATH"
 
+usage() {
+    if [ -n "$1" ]
+    then
+	echo $@
+	xsts=-1
+    fi
+
+    echo $MyName '$options $mainfile $otherfiles'
+    echo '	where options are one or more of the following:'
+    echo '	-W	only compile whiley to generate C'
+    echo '	-B	skip the whiley compilation and build from the .c'
+    echo '	-C	Compile Whiley and compile c to .o file'
+    echo '	-S	Compile Whiley and compile c to .s file'
+    echo '	-D	Sprinkle the .c file with diagnostic comments (default)'
+    echo
+    echo 'only the main file will be processed by the Whiley compiler'
+    echo 'other files are assumed to be .c, .s, .o, or libraries'
+    echo 'Any executable will be named with the basename of $mainfile'
+    exit ${xsts:0}
+}
+
+two=:
 FileName=
 Other=
 Opts=
@@ -67,11 +105,13 @@ ToO=:
 ToX=:
 #BuildOnly=false
 ToS='-c'
+Debug=false
+Decho=:
 
 while [[ $# -gt 0 ]]
 do
     case "$1" in
-    -B)		# only do whiley compilation
+    -B)		# skip the whiley compilation and build from the .c
 	    #BuildOnly=:
 	    WYCC=:
 	    ;;
@@ -85,9 +125,16 @@ do
 	    ToX=false
 	    ToS='-s'
 	    ;;
+    -D)		# Compile Whiley with gobs of diagnostic comments
+	    Debug=:
+	    ;;
+    -h)		# Give the usage message
+	    two="usage"
+	    ;;
     -*)
 	    #Opts="$Opts $1"
-	    echo "unknown option '$1'"
+	    #echo "unknown option '$1'"
+	    two="usage unknown option '$1' "
 	    ;;
     *)
 	    if [[ -z "$FileName" ]]
@@ -100,10 +147,16 @@ do
     shift
 done
 
+if $Debug
+then
+    Decho=echo
+fi
 BaseName=${FileName%%.*}
 CName=${BaseName}.c
-echo "wjcc  filename is '$FileName', Opts is '$Opts', Other is '$Other'"
-echo "Basename is $BaseName and CName is $CName"
+$Decho "wjcc  filename is '$FileName', Opts is '$Opts', Other is '$Other'"
+$Decho "Basename is $BaseName and CName is $CName"
+
+$two
 
 # if [ "$WYCC" = ':' ]
 # then
