Implemented wycc_cow_map. Fixed typo in clib/Makefile Changed builder to bump the reference count on arguments at routine entry. Change wycc_deref_box to take a flag to optionally skip Panic for dead references. found and (likely) fixed a race condition in the test harness - NOT!!!!. SetComprehension_Valid_9.sysout does not match the output JUnit results: 2 errors, 0 failures, 52 ignored, out of 460. Yield: 406 tests passing.

diff --git a/bin/wyone b/bin/wyone
--- a/bin/wyone
+++ b/bin/wyone
@@ -1,3 +1,4 @@
+#!/bin/bash
 #!/bin/sh
 
 # This file is part of the Whiley Development Kit (WDK).
@@ -38,10 +39,19 @@ esac
 if $cygwin; then
     # under cygwin the classpath separator must be ";"
     LIBDIR=`cygpath -pw "$LIBDIR"`
-    WHILEY_CLASSPATH="$LIBDIR/wyjc.jar;$CLASSPATH"
+    PATHSEP=";"
 else
     # under UNIX the classpath separator must be ":"
-    WHILEY_CLASSPATH="$LIBDIR/wyjc.jar:$CLASSPATH"
+    PATHSEP=":"
 fi
+
+tmp=$(echo $LIBDIR/wyjc*.jar)
+case "$tmp" in
+*\**)
+    echo "wyjc.jar not found" >&2
+    exit 2
+    ;;
+esac
+WHILEY_CLASSPATH="${tmp##* }${PATHSEP}$CLASSPATH"
 
 java -server -Xmx128M -cp "$WHILEY_CLASSPATH" wyone.Main "$@"
